# Generated by Django 4.1.7 on 2023-03-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_team', models.CharField(max_length=100)),
                ('last_update', models.CharField(max_length=100)),
                ('away_price', models.IntegerField()),
                ('home_price', models.IntegerField()),
            ],
        ),
    ]
