# Generated by Django 4.1.7 on 2023-03-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_user', models.CharField(max_length=100)),
                ('comment_date', models.DateField(blank=True)),
                ('comment', models.TextField(max_length=250)),
            ],
        ),
    ]
