# Generated by Django 4.1.7 on 2023-03-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='game_choice',
            field=models.CharField(default='Bucks', max_length=100),
            preserve_default=False,
        ),
    ]
